name: GCC build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with GCC
        run: |
          gcc -std=c11 -Wall -Wextra -O2 "Scientific Calculator.c" -o calculator -lm
      - name: Smoke test
        run: ./calculator || true
